export const STATUS_CODE_SUCCESS = 200;
export const STATUS_CODE_GENERIC_ERROR = 500;
export const STATUS_CODE_NOT_FOUND = 404;
export const STATUS_CODE_BAD_REQUEST = 400;
export const STATUS_CODE_UNPROCESSING = 422;
export const STATUS_CODE_FORBIDEN = 403;
export const STATUS_CODE_NOCONTENT = 204;
