name: ci

on:
  push:
    branches:
      - 'deploy-to-docker-hub'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/my-repo:auth-server-v2